version: '3.8'

services:  
  db:
    image: mysql:latest # use latest version of mysql
    container_name: mysqldb # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: # add default values, see docs for more info.
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ykn9080
      MYSQL_PASSWORD: ykn9080
      MYSQL_DATABASE: imcdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes: # add persistent data even if container is removed.
  my-db: